# Generated by Django 5.2.17 on 2026-09-07 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_upn',
            field=models.CharField(blank=True, help_text='UPN completo no formato usuario@dominio (ex.: cpf@dominio). O sufixo é livre — floresta multi-domínio.', max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Informe o UPN completo no formato usuario@dominio (ex.: cpf@dominio).', regex='^[^@\\s]+@[^@\\s]+$')], verbose_name='UPN do Active Directory'),
        ),
    ]
