# Generated by Django 5.2.17 on 2026-09-08 11:02

from typing import Any

from django.db import migrations, models


def seed_doctor_specialties(apps: Any, schema_editor: Any) -> None:
    """Semeia os 4 subtipos de médico com nomes congelados (slice 001, R2).

    Histórico congelado de propósito: os nomes vivem aqui, não em código vivo
    — a coerência com ``procedure_catalog.VALID_DOCTOR_SUBTYPES`` é garantida
    por teste de invariante (R5), nunca por import nesta migration. O seed é
    idempotente (get_or_create) para bancos incrementais e novos.
    """
    DoctorSpecialty = apps.get_model("accounts", "DoctorSpecialty")
    for name in ("angio", "neuro", "cardio", "radio"):
        DoctorSpecialty.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ad_upn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Subtipo de médico',
                'verbose_name_plural': 'Subtipos de médico',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.doctorspecialty'),
        ),
        migrations.RunPython(seed_doctor_specialties, migrations.RunPython.noop),
    ]
