# Generated by Django 5.2.17 on 2026-09-10 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_specialty'),
        ('cases', '0009_case_correction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('final_reply_posted', 'Resposta final publicada'), ('scheduler_requested', 'Caso pronto para agendamento'), ('scheduling_reopened', 'Caso reaberto por intercorrência')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('body_preview', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.caseevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='accounts_us_recipie_67cc80_idx'), models.Index(fields=['case', 'created_at'], name='accounts_us_case_id_539c73_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event'), name='uniq_notif_recipient_event')],
            },
        ),
    ]
