# Generated by Django 5.2.17 on 2026-09-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('final_reply_posted', 'Resposta final publicada'), ('scheduler_requested', 'Caso pronto para agendamento'), ('scheduling_reopened', 'Caso reaberto por intercorrência'), ('administratively_closed', 'Caso encerrado administrativamente')], max_length=30),
        ),
    ]
