# Generated by Django 5.2.17 on 2026-09-09 16:55

import apps.attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0009_case_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=apps.attachments.models.case_attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('processed', 'Processado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('extraction_method', models.CharField(blank=True, choices=[('local_pdf', 'Extração local (PDF)'), ('vision', 'OCR externo (vision)')], max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('anonymized_text', models.TextField(blank=True)),
                ('pseudonym_map', models.JSONField(blank=True, default=dict)),
                ('patient_match', models.CharField(blank=True, choices=[('match', 'Coincidente'), ('mismatch', 'Divergente'), ('unknown', 'Desconhecido')], max_length=10, null=True)),
                ('verification_summary', models.TextField(blank=True)),
                ('verification_evidence', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
