# Generated by Django 5.2.17 on 2026-09-07 09:55

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('NEW', 'Novo'), ('PDF_EXTRACTING', 'Extraindo PDF'), ('ANONYMIZING', 'Anonimizando'), ('LLM_EXTRACTING', 'Extraindo via LLM'), ('LLM_SUMMARIZING', 'Sumarizando via LLM'), ('AWAITING_DOCTOR', 'Aguardando decisão médica'), ('DOCTOR_DENIED', 'Negado pelo médico'), ('DOCTOR_ACCEPTED', 'Aceito pelo médico'), ('SCHEDULER_REQUESTED', 'Agendamento solicitado'), ('AWAITING_SCHEDULING', 'Aguardando confirmação de agendamento'), ('SCHEDULING_CONFIRMED', 'Agendamento confirmado'), ('SCHEDULING_DENIED', 'Agendamento negado'), ('FAILED', 'Falha de processamento'), ('FINAL_REPLY_POSTED', 'Resposta final publicada'), ('AWAITING_NIR_ACK', 'Aguardando ciência do NIR'), ('CLEANING', 'Limpando dados'), ('CLEANED', 'Caso concluído')], default='NEW', max_length=30, protected=True)),
                ('agency_record_number', models.CharField(blank=True, max_length=20)),
                ('agency_record_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_fsm.FSMModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('user', 'Usuário'), ('system', 'Sistema')], max_length=10)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
