# Generated by Django 5.2.17 on 2026-09-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(max_length=20)),
                ('declared_by_nir', models.BooleanField(default=False)),
                ('detection_status', models.CharField(choices=[('pending', 'Pendente'), ('detected', 'Detectado'), ('not_detected', 'Não detectado')], default='pending', max_length=20)),
                ('doctor_disposition', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('denied', 'Negado')], default='pending', max_length=20)),
                ('doctor_reason', models.TextField(blank=True)),
                ('doctor_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='cases.case')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'procedure_type'), name='uniq_case_procedure_type')],
            },
        ),
    ]
