# Generated by Django 5.2.17 on 2026-09-07 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_lock_context_case_lock_role_case_lock_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCommunicationMessage',
            fields=[
                ('message_type', models.CharField(choices=[('user', 'Usuário'), ('system', 'Sistema')], default='user', max_length=20)),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_role', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField()),
                ('system_event_type', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_communication_messages', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_messages', to='cases.case')),
                ('source_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_notice', to='cases.caseevent')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='cases_casec_case_id_44d48d_idx')],
            },
        ),
    ]
