# Generated by Django 5.2.17 on 2026-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_sesab_header_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='origin_unit',
            field=models.CharField(blank=True, max_length=128, default=""),
        ),
    ]
