# Generated by Django 5.2.17 on 2026-09-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'version'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_llm_prompt_name_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='uniq_llm_prompt_active_per_name')],
            },
        ),
    ]
